let area1 = [
  { landmark: "Kalewadi - Jyotiba Garden (S)", area: "Kalewadi ⁣" },
  { landmark: "Kiwale - Mukai Chowk (S)", area: "Kiwale ⁣" },
  { landmark: "Warje - Vinayak Hospital (L)", area: "Warje ⁣" },
  { landmark: "Hinjewadi - Andhra Mess (S)", area: "Hinjewadi ⁣" },
  { landmark: "Baner - Pashan Link Road (S)", area: "Pashan ⁣" },
  { landmark: "Chikhli - HDFC Corner (M)", area: "Chikhli ⁣" },
  { landmark: "Thergoan - Gavane Hospital (S)", area: "Thergaon ⁣" },
  { landmark: "Akurdi - Gurudwara Chowk (S)", area: "Akurdi" },
  { landmark: "Akurdi - Mhalsakant chowk (S)", area: "Akurdi" },
  { landmark: "Akurdi - Railway Station (S)", area: "Akurdi" },
  { landmark: "Akurdi-Bijlee Ngr WaterTank(S)", area: "Akurdi" },
  { landmark: "Akurdi-PMTstop Force motors(S)", area: "Akurdi" },
  { landmark: "Akurdi - Railway Station (S)", area: "Akurdi Station" },
  { landmark: "Akurdi - DY Patil college (S)", area: "Akurdi Station" },
  { landmark: "Aundh - Bremen Circle (M)", area: "Aundh ⁣" },
  { landmark: "Aundh - Convergys (M)", area: "Aundh ⁣" },
  { landmark: "Aundh - DAV public School (M)", area: "Aundh ⁣" },
  { landmark: "Aundh - Hotel Pichola (M)", area: "Aundh ⁣" },
  { landmark: "Aundh - Hotel Sarja (M)", area: "Aundh ⁣" },
  { landmark: "Aundh - Medi point (M)", area: "Aundh ⁣" },
  { landmark: "Aundh - Parihar Chowk (M)", area: "Aundh ⁣" },
  { landmark: "Aundh - Sony World (M)", area: "Aundh ⁣" },
  { landmark: "Aundh Road - Pune IT park (M)", area: "Aundh ⁣" },
  { landmark: "Aundh- Sakal Nagar Corner(M)", area: "Aundh ⁣" },
  { landmark: "Aundh Road - Spicer College(M)", area: "Aundh ⁣" },
  { landmark: "Aundh Road - Ambedkar Chowk(M)", area: "Aundh ⁣" },
  { landmark: "Aundh-Police station corner(M)", area: "Aundh ⁣" },
  { landmark: "Balewadi - Elite Empire (S)", area: "Balewadi ⁣" },
  { landmark: "Balewadi - Mitcon (S)", area: "Balewadi ⁣" },
  { landmark: "Balewadi - Orchid Hotel (S)", area: "Balewadi ⁣" },
  { landmark: "Baner - Food Bazzar (M)", area: "Baner" },
  { landmark: "Baner - Hotel Green Park (M)", area: "Baner ⁣" },
  { landmark: "Baner - Hotel Sadanand (M)", area: "Baner ⁣" },
  { landmark: "Baner - Prime Rose Mall (M)", area: "Baner ⁣" },
  { landmark: "Baner - Kapil Malhar (M)", area: "Baner ⁣" },
  { landmark: "Bavdhan - DSK Ranwara (M)", area: "Bavdhan" },
  { landmark: "Bavdhan - Maratha Mandir (M)", area: "Bavdhan" },
  { landmark: "Bavdhan - Police Chowki (M)", area: "Bavdhan" },
  { landmark: "Bhosari - Shivaji Statue (M)", area: "Bhosari ⁣" },
  { landmark: "Bopkhel - Ganesh Temple (L)", area: "Bopkhel ⁣" },
  { landmark: "Bopkhel - TCL Main Gate (L)", area: "Bopkhel ⁣" },
  { landmark: "Camp - Cafe Majestic (L)", area: "Camp ⁣" },
  { landmark: "Camp - Quarter gate circle (L)", area: "" },
  { landmark: "Chikhli - KSB Chowk (M)", area: "Chikhli ⁣" },
  { landmark: "Chikhli - Mahabali Chowk (M)", area: "Chikhli ⁣" },
  { landmark: "Chikhli - Mathura Sweets (M)", area: "Chikhli ⁣" },
  { landmark: "Chikhli - Sane Chowk (M)", area: "Chikhli ⁣" },
  { landmark: "Chikhli - Shahu nagar RTO (M)", area: "Chikhli ⁣" },
  { landmark: "Chinchwad - Dharshan Hall (M)", area: "Chinchwad ⁣" },
  { landmark: "Chinchwad - Morya Hospital (S)", area: "Chinchwad ⁣" },
  { landmark: "Dehu Road - Hotel Savana (M)", area: "Dehuroad ⁣" },
  { landmark: "Dhankwadi - Trimurti Chowk (L)", area: "Dhankawadi ⁣" },
  { landmark: "Dhanori - Bharat Dhaba (L)", area: "Dhanori ⁣" },
  { landmark: "Dhanori - Jakat naka (L)", area: "Dhanori ⁣" },
  { landmark: "Dhayari - DSK Vishwa (L)", area: "Dhayri ⁣" },
  { landmark: "Dighi - Dighi Jakat Naka (L)", area: "Dighi ⁣" },
  { landmark: "Ganj Peth - Police Chowky (L)", area: "Ganj Peth ⁣" },
  { landmark: "Ghorpadi Peth - Mominpura (L)", area: "Ghorpadi Peth ⁣" },
  { landmark: "Ghorpadi Peth - PMC Colony (L)", area: "Ghorpadi Peth ⁣" },
  { landmark: "Dhankawadi - Hatti Chowk (L)", area: "Dhankawadi ⁣" },
  { landmark: "Hinjewadi - Andhra Mess (S)", area: "Hinjewadi ⁣" },
  { landmark: "Hinjewadi - Mezza9 hotel (S)", area: "Hinjewadi ⁣" },
  { landmark: "Hinjewadi - Shivaji Chowk (S)", area: "Hinjewadi ⁣" },
  { landmark: "Kalewadi - Tapkir Chowk (S)", area: "Kalewadi ⁣" },
  { landmark: "Kalewadi - Lucky Bakery (S)", area: "Kalewadi ⁣" },
  { landmark: "Kalewadi - Hotel Ambience (S)", area: "Kalewadi ⁣" },
  { landmark: "Thergaon - 16 N0 Bus stop (S)", area: "Thergaon ⁣" },
  { landmark: "Kalewadi - Pachpir Chowk (S)", area: "Kalewadi ⁣" },
  { landmark: "Kalewadi - Rahatni Phata (S)", area: "Kalewadi ⁣" },
  { landmark: "Kasarwadi - CME Main Gate (M)", area: "Kasarwadi ⁣" },
  { landmark: "Kondhwa - Jyoti Restaurant (L)", area: "Kondhwa ⁣" },
  { landmark: "Kothrud - Badhai Sweets (L)", area: "Kothrud ⁣" },
  { landmark: "Kothrud - Bandal Capital (L)", area: "Kothrud ⁣" },
  { landmark: "Kothrud - Dahanukar Circle (L)", area: "Kothrud ⁣" },
  { landmark: "Kothrud - Eklavya Collage (L)", area: "Kothrud ⁣" },
  { landmark: "Kothrud - Opp Karishma (L)", area: "Kothrud ⁣" },
  { landmark: "Kothrud - Shivaji Statue (L)", area: "Kothrud ⁣" },
  { landmark: "Lohegaon - Police Chowky (L)", area: "Lohegaon ⁣" },
  { landmark: "Malwadi - Ganpati Matha (L)", area: "Uttam Nagar ⁣" },
  { landmark: "Marunji - Laxmi Chowk (S)", area: "Marunji ⁣" },
  { landmark: "Mundhva - Passport Office(L)", area: "Mundhwa ⁣" },
  { landmark: "Narhe - Zeal College(L)", area: "Narhe ⁣" },
  { landmark: "Nda Gate - Kondhve Dhavade (L)", area: "Khondwe Dhwade ⁣" },
  { landmark: "Pashan - NCL Colony (M)", area: "Pashan ⁣" },
  { landmark: "Paud Road - More Vidyalaya (L)", area: "Paud Road ⁣" },
  { landmark: "Paud Road - SNDT Bus Stop (L)", area: "Paud Road ⁣" },
  { landmark: "Paud Road - Vanaz Corner (L)", area: "Paud Road ⁣" },
  { landmark: "Pimpri - Ambedkar Chowk (M)", area: "Pimpri ⁣" },
  { landmark: "Pimpri - Deluxe chowk (S)", area: "Pimpri ⁣" },
  { landmark: "Pimpri - PCMC Main Bulding (M)", area: "" },
  { landmark: "Pimpri - Sai Chowk (S)", area: "Pimpri ⁣" },
  { landmark: "Pimpri - Shagun Chowk (S)", area: "Pimpri ⁣" },
  { landmark: "Pimpri - Tapovan mandir (S)", area: "Pimpri ⁣" },
  { landmark: "Pradhikaran - Bhel Chowk (S)", area: "Pradhikaran Nigdi ⁣" },
  { landmark: "Pune Station - Sohrab Hall (L)", area: "" },
  { landmark: "Rahatni - Hotel Sitara (S)", area: "Kalewadi ⁣" },
  { landmark: "Rasta Peth - Mseb Building (L)", area: "Rasta Peth ⁣" },
  { landmark: "Ravet - Lotus Shoppe Ravet (S)", area: "" },
  { landmark: "Ravet - Nano Homes (S)", area: "Ravet ⁣" },
  { landmark: "Sangamwadi - Bus Stop (L)", area: "Sangamwadi ⁣" },
  { landmark: "SB Road - Opp Hotel Sahara (L)", area: "Senapati Bapat Road ⁣" },
  { landmark: "Shivane - Shivne bus stop (L)", area: "Uttam Nagar ⁣" },
  { landmark: "Sus Road - Balaji Mandir (S)", area: "Sus Road ⁣" },
  { landmark: "Sus Road - Pashankar Auto (S)", area: "Pashan ⁣" },
  { landmark: "Sus Road - Sai Chowk (S)", area: "Sus Road ⁣" },
  { landmark: "Swargate - Varadshree Hall (L)", area: "Swargate ⁣" },
  { landmark: "Thergoan - Gavane Hospital (S)", area: "Thergaon ⁣" },
  { landmark: "Tingre Nagar - Anup Bakery (L)", area: "Tingre Nagar ⁣" },
  { landmark: "Tingre Nagar - Kekan gas (L)", area: "Tingre Nagar ⁣" },
  { landmark: "Uttamnagar - Ahire Gate (L)", area: "Uttam Nagar ⁣" },
  { landmark: "Vimanagar - Novotel Hotel (L)", area: "VIMANAGAR" },
  { landmark: "Vishrant Wadi - RTO (L)", area: "Yerwada ⁣" },
  { landmark: "Wakad - Mont Vert Corner (S)", area: "Wakad ⁣" },
  { landmark: "Wakad - Corporation School (S)", area: "Wakad ⁣" },
  { landmark: "Wakad - Datta Mandir (S)", area: "Wakad ⁣" },
  { landmark: "Wakad - Hotel Soundarya (S)", area: "Wakad ⁣" },
  { landmark: "Wakad - Mauli Chowk (S)", area: "Wakad ⁣" },
  { landmark: "Wakad - Shiv colony gate (S)", area: "Wakad ⁣" },
  { landmark: "Warje - Popular Junction (L)", area: "Warje ⁣" },
  { landmark: "Warje - Warje Naka (L)", area: "Warje ⁣" },
  { landmark: "Warje - Wonder funkey (L)", area: "Warje ⁣" },
  { landmark: "Yerawada - Gunjan Theatre (L)", area: "Yerawada ⁣" },
  { landmark: "Khadki - Martyr Cemetery (L)", area: "Khadaki ⁣" },
  { landmark: "Infosys PH-2 Gate-4 (S)", area: "Hinjewadi ⁣" },
  { landmark: "Ghotawde Phata-Calyx Navyangan", area: "" },
  { landmark: "Baner - Kalamkar Chowk (M)", area: "Baner ⁣" },
  { landmark: "Viman Nagar - Opp Dorabjee (L)", area: "Viman Nagar ⁣" },
  { landmark: "Bhosari - Shashtri Chowk (L)", area: "Bhosari ⁣" },
  { landmark: "Baner - Opp NEXA Service (S)", area: "Baner ⁣" },
  { landmark: "Tathwade- Akshara School (S)", area: "Tathwade ⁣" },
  { landmark: "Maan Road - Joyville (OOB)", area: "" },
  { landmark: "Hinjewadi - Kasturi Chowk (S)", area: "Hinjewadi ⁣" },
  { landmark: "Lohegaon - Kalwad Wasti (L)", area: "Lohegaon ⁣" },
  { landmark: "Kondhwa - Rajyog Lawns (L)", area: "Kondhwa ⁣" },
  { landmark: "Jagtap Dairy Signal (S)", area: "JAGTAP DAIRY ⁣" },
  { landmark: "Kharadi - Fortune House (L)", area: "Kharadi ⁣" },
  { landmark: "Viman Nagar - 10 Biz Park (L)", area: "Viman Nagar ⁣" },
  { landmark: "Ajmera-Masulkar-HDFC ATM-(M)", area: "Ajmera" },
  { landmark: "Ajmera-MorwadiGharonda Hotel-S", area: "Ajmera" },
  { landmark: "Ajmera - Vastu Udyog Corner(M)", area: "Ajmera" },
  { landmark: "Mai Mangeshkar Hospital (L)", area: "Warje ⁣" },
  { landmark: "Akurdi - Bajaj Auto Gate (S)", area: "Yamuna Nagar Nigdi ⁣" },
  { landmark: "AmbegaonPathar-PrernaSchool(L)", area: "Ambegaonpathar " },
  { landmark: "PG-Ramkrishna Mangal Hall (M)", area: "Pimple Gurav ⁣" },
  { landmark: "VimanNagar-HotelShriKrishna(L)", area: "Viman Nagar ⁣" },
  { landmark: "Sb Road - Dominos Pizza (M)", area: "Senapati Bapat Road ⁣" },
  { landmark: "Ambegoan Near D-mart(L)", area: "Ambegaon Budruk left ⁣" },
  { landmark: "Aundh-Siddharth Ngr market (M)", area: "" },
  { landmark: "Chinchwad-Ranka Jewellers", area: "" },
  { landmark: "Aundh Road - Ganesh Temple (M)", area: "Aundh Road " },
  { landmark: "BTKawde-Nr Citadal Soc Gate(L)", area: "Ghorpadi ⁣" },
  { landmark: "Balaji Ngr - Ellora palace (L)", area: "Balaji Nagar ⁣" },
  { landmark: "Balaji Nagar - K K Market (L)", area: "Balaji Nagar ⁣" },
  { landmark: "Balewadi-ComfortZONE Corner(S)", area: "Balewadi ⁣" },
  { landmark: "Balewadi-Savata Mali Temple(S)", area: "" },
  { landmark: "Baner-Ganraj Mangal Hall (M)", area: "Baner ⁣" },
  { landmark: "Baner - Hotel Mahabaleshwar(M)", area: "Baner ⁣" },
  { landmark: "Baner-Lifecare Medico (S)", area: "Baner ⁣" },
  { landmark: "Baner - Savata mali temple(S)", area: "" },
  { landmark: "Baner - Sindh Society gate (M)", area: "Baner ⁣" },
  { landmark: "Bavdhan-Chellaram Hospital (M)", area: "Bavdhan" },
  { landmark: "Bavdhan-Zinnea Appt gate (M)", area: "Bavdhan" },
  { landmark: "Bharti Vidyapeeth Main Gate(L)", area: "BhartiVidyapeeth ⁣" },
  { landmark: "Bhawani Peth-DhobiGhat Corn(L)", area: "Bhawani Peth ⁣" },
  { landmark: "Bhawani Peth-Ramoshi Gate (L)", area: "Bhawani Peth ⁣" },
  {
    landmark: "Bhoirwadi-TCS Circle (S)",
    area: "Hinjewadi Megapolis Phase 03",
  },
  { landmark: "Bhosari-Anand Hospital stop(M)", area: "Bhosari ⁣" },
  { landmark: "Bhosari-Hotel Vishwa Vilas (M)", area: "Bhosari ⁣" },
  { landmark: "Bhosari-JaiGanesh Samrajya (L)", area: "Bhosari ⁣" },
  { landmark: "Bhumkar Chowk-Chandra Mauli(S)", area: "Bhumkar Wasti ⁣" },
  { landmark: "BhumkarWasti-SixSeaterstand(S)", area: "Bhumkar Wasti ⁣" },
  { landmark: "BhumkarWasti - Poona Bakery(S)", area: "Bhumkar Wasti ⁣" },
  { landmark: "Bibwewadi - Near BOM Bank (L)", area: "Bibwewadi ⁣" },
  { landmark: "Bibwewadi-Gangadham Chowk (L)", area: "Bibwewadi ⁣" },
  { landmark: "Bibwewadi-Balaji Amruttulya(L)", area: "Bibwewadi ⁣" },
  { landmark: "Bibwewadi-MaheshSocietyGate(L)", area: "Bibwewadi ⁣" },
  { landmark: "Bijli Nagar-Hanuman Sweets (S)", area: "Bijlinagar ⁣" },
  { landmark: "Bopodi-Chajjed Petrol Pump (M)", area: "Bhau Patil Road" },
  { landmark: "Budhwar Peth-PrabhatThetere(L)", area: "Budhwar Peth ⁣" },
  { landmark: "Bund Guarden-WadiaColl Gate(L)", area: "Bund garden" },
  { landmark: "Camp - Coportion Bank (L)", area: "Camp ⁣" },
  { landmark: "Camp - Lal Deoul (L)", area: "" },
  { landmark: "Chandan NGR - NEI PMT Stop (L)", area: "Chandan Nagar ⁣" },
  { landmark: "Chandan NGR-Sangharsh Chowk(L)", area: "Chandan Nagar ⁣" },
  { landmark: "Chandan NGR - Sunita Nagar (L)", area: "Chandan Nagar ⁣" },
  { landmark: "Chandan NGR-Tata Guard Room(L)", area: "Chandan Nagar ⁣" },
  { landmark: "ChandaniChowk-Highway Stop(M)", area: "Fatimanagar ⁣" },
  { landmark: "ChandaniChowk-VedBhavan Cor(M)", area: "ChandaniChowk ⁣" },
  { landmark: "Chikhli - Cherry Sweet Mart(M)", area: "Chikhali ⁣" },
  { landmark: "Chikhli - Indica Gate No 2 (M)", area: "Chikhali ⁣" },
  { landmark: "Chikhli-Kasturi Market Stop(M)", area: "Chikhli ⁣" },
  { landmark: "Chikhli - Thermax Chowk (M)", area: "Chikhali ⁣" },
  { landmark: "Chinchwad-Bhoir Ngr School (S)", area: "Chinchwad ⁣" },
  { landmark: "Chinchwad - Jai Hind Pump (S)", area: "Chinchwad ⁣" },
  { landmark: "Chinchwad - KeshavNGRSchool(S)", area: "Chinchwad ⁣" },
  { landmark: "Chinchwad - Lokmanya Hosp (S)", area: "Chinchwad ⁣" },
  { landmark: "Chinchwad-Gawade Pump (M)", area: "Chinchwad ⁣" },
  { landmark: "Chinchwad-PNG ChapekarChowk(S)", area: "Chinchwad ⁣" },
  { landmark: "Chinchwad-PCMC Natyagraha (S)", area: "Chinchwad ⁣" },
  { landmark: "Chinchwad-Premlok Park-TVS (S)", area: "Chinchwad ⁣" },
  { landmark: "Chinchwad-Yashopuram Corn (S)", area: "Chinchwad ⁣" },
  { landmark: "Chinchwad-Mohan Nagar Chowk(M)", area: "" },
  { landmark: "Corporation-Balghandharva (L)", area: "Shivaji Nagar ⁣" },
  { landmark: "Corporation-Sawarkar Bhavan(L)", area: "Shivaji Nagar ⁣" },
  { landmark: "DandekarPul-Ramkrishna Math(L)", area: "DANDEKAR BRIDGE ⁣" },
  { landmark: "Dange Chowk-Bhoir Hospital (S)", area: "DANGE CHOWK" },
  { landmark: "Dange Chowk-Pratibha Motore(S)", area: "DANGE CHOWK" },
  { landmark: "Dapodi-Dapodi Main bus stop(M)", area: "Dapodi ⁣" },
  { landmark: "Deccan-Honkong lane Corn (L)", area: "Deccan ⁣" },
  { landmark: "Deccan-Hotel Oakwood (L)", area: "" },
  { landmark: "Deccan-Spencer (L)", area: "Deccan ⁣" },
  { landmark: "Deccan-Bombay Sappers Chowk(L)", area: "Deccan ⁣" },
  { landmark: "Deccan-Holkar Bridge Corner(L)", area: "Deccan ⁣" },
  { landmark: "Dehu Road-Central Hotel (M)", area: "Dehuroad ⁣" },
  { landmark: "Dehu Road-Samir Lawns (S)", area: "Dehuroad ⁣" },
  { landmark: "Dehu Road-Shinde Petrol Pump-M", area: "Dehuroad ⁣" },
  { landmark: "DehuRoad-ShitalaMata Mandir(M)", area: "Dehuroad ⁣" },
  { landmark: "DehuRoad-Ordnance factory (M)", area: "Dehuroad ⁣" },
  { landmark: "Dhanori-Amba Nagari Society(L)", area: "Dhanori ⁣" },
  { landmark: "Dhanori-Palladium Society (L)", area: "Dhanori ⁣" },
  { landmark: "Dhayari-Dhareshwar Karyalay(L)", area: "Dhayri ⁣" },
  { landmark: "Dhayari-Last PMT Bus Stop (L)", area: "Dhayri ⁣" },
  { landmark: "Dhayari- Abhiruchi resort (L)", area: "Dhayri ⁣" },
  { landmark: "Dhayari-Raikar NGR Bus Stop(L)", area: "Dhayri ⁣" },
  { landmark: "DholePatil RD-Holiday Inn (L)", area: "Dhole Patil Road ⁣" },
  { landmark: "DholePatil RD-HotelFoodland(L)", area: "Dhole Patil Road ⁣" },
  { landmark: "DholePatil RD-Blind School (L)", area: "Dhole Patil Road ⁣" },
  { landmark: "Dighi-GajananMaharaj Stop (L)", area: "Dighi ⁣" },
  { landmark: "Dighi-B U Bhandari Skyline (L)", area: "Dighi ⁣" },
  { landmark: "Dighi-DattaNGR MedPlusMedi (L)", area: "Dighi ⁣" },
  { landmark: "Erandwana-Karnataka school (L)", area: "Erandwane ⁣" },
  { landmark: "Erandwane-Mahendale Garage (L)", area: "Erandwane ⁣" },
  { landmark: "FatimaNGR-EmpressGardengate(L)", area: "Fatimanagar ⁣" },
  { landmark: "Fatima Nagar-Big Bazaar (L)", area: "Fatimanagar ⁣" },
  { landmark: "Ghorpadi-Vatsalya School (L)", area: "Ghorpadi ⁣" },
  { landmark: "Ghorpadi-Mahalxmi Temple (L)", area: "Ghorpadi ⁣" },
  { landmark: "Ghorpadi- War Memorial (L)", area: "" },
  { landmark: "Ghorpadi Peth-GhorpadeUdyan(L)", area: "Ghorpadi Peth ⁣" },
  { landmark: "Gultekadi-Giridhar Bhavan (L)", area: "Gultekadi ⁣" },
  { landmark: "GuruwarPeth-Mithganj Chowky(L)", area: "Guruwar Peth ⁣" },
  { landmark: "GuruwarPeth-RashtrbhushnCk(L)", area: "Guruwar Peth ⁣" },
  { landmark: "Hadapsar-Gadital-PMTBusStop(L)", area: "Hadapsar ⁣" },
  { landmark: "Hinjawadi PH 3-Megapolis (S)", area: "Hinjewadi ⁣" },
  { landmark: "Hinjewadi-Green Olive CHS (S)", area: "Hinjewadi ⁣" },
  { landmark: "Hinjewadi-Blue Ridge Chowk (S)", area: "Hinjewadi ⁣" },
  { landmark: "Hinjewadi-BeverlyHills Gate(S)", area: "Hinjewadi ⁣" },
  { landmark: "Hinjewadi-PNB Bank (S)", area: "Hinjewadi ⁣" },
  { landmark: "Hinjewadi-Sakhre Wasti Road(S)", area: "Hinjewadi ⁣" },
  { landmark: "Hinjewadi-TCG Gate", area: "Hinjewadi" },
  { landmark: "Hinjewadi PH 1-Infy Gate-1 (S)", area: "Hinjewadi ⁣" },
  { landmark: "Hinjewadi PH 2-Wipro Circle(S)", area: "Hinjewadi ⁣" },
  {
    landmark: "Indrayni NGR-Hotel Haveli (L)",
    area: "Indrayani Nagar Bhosari ⁣",
  },
  { landmark: "Indrayni NGR-SidhivinaykCHK(L)", area: "Bhosari ⁣" },
  { landmark: "Kalas-Hotel Banana Leaf (L)", area: "Kalas ⁣" },
  { landmark: "Kalewadi-Dhondiraj Karyalay(S)", area: "Kalewadi ⁣" },
  { landmark: "KalewadiPhata-GreenPeasRest(S)", area: "Kalewadi ⁣" },
  { landmark: "Kalewadi Phata After Signal(S)", area: "Kalewadi ⁣" },
  { landmark: "Kalyani NGR-Fortaleza Gate (L)", area: "Kalyani Nagar ⁣" },
  { landmark: "Kalyani NGR-Shastri Chowk (L)", area: "Kalyani Nagar ⁣" },
  { landmark: "Kalyani NGR-Ramwadi naka (L)", area: "Kalyani Nagar ⁣" },
  { landmark: "Karve NGR-Cummins college (L)", area: "Karve nagar ⁣" },
  { landmark: "Karve NGR-KakdeCityMainGate(L)", area: "Karve nagar ⁣" },
  { landmark: "Karve NGR-Karve StatueBOM (L)", area: "Karve nagar ⁣" },
  { landmark: "Karve NGR-Matoshree OldAge (L)", area: "Karve nagar ⁣" },
  { landmark: "Karve NGR-Alankar Police St(L)", area: "Karve nagar ⁣" },
  { landmark: "Karve NGR-KPITMahadevMandir(L)", area: "Karve nagar ⁣" },
  { landmark: "Karve NGR-Vitthal Mandir (L)", area: "Karve nagar ⁣" },
  { landmark: "Karve NGR-PratidnyaHallCorn(L)", area: "Karve nagar ⁣" },
  { landmark: "Karve NGR-Swapnashilp Soc (L)", area: "Karve nagar ⁣" },
  { landmark: "Karve NGR-UnitedWesternBank(L)", area: "Karve nagar ⁣" },
  { landmark: "Hingane Home Colony Corner (L)", area: "Karve nagar ⁣" },
  { landmark: "Karve Nagar Chowk (L)", area: "Karve nagar ⁣" },
  { landmark: "Kasarwadi-Near Shere Punjab(M)", area: "Kasarwadi ⁣" },
  { landmark: "KaspateVasti-ChatrapatiChowk-S", area: "Kaspate Wasti ⁣" },
  { landmark: "KaspateVasti-Mankar Chowk (S)", area: "Kaspate Wasti ⁣" },
  { landmark: "Katraj-Datta NGR Wondercity(L)", area: "Katraj ⁣" },
  { landmark: "Katraj-Datta Ngr Bus Stop (L)", area: "Katraj ⁣" },
  { landmark: "Katraj-DuttaNGR Under Pass (L)", area: "Katraj ⁣" },
  { landmark: "Katraj-JSPM Group of India (L)", area: "Katraj ⁣" },
  { landmark: "KatrajKondhwa Rd-IOC Pump (L)", area: "Katraj ⁣" },
  { landmark: "Kondhwa-Shatrunjay Temple(L)", area: "Kondhwa ⁣" },
  { landmark: "Katraj- RajasSociety(L)", area: "Katraj ⁣" },
  { landmark: "Khadki-Opp Police station (M)", area: "Khadaki ⁣" },
  { landmark: "Khadki Bazar-Bus depo (M)", area: "Khadaki ⁣" },
  { landmark: "Kharadi-Eon IT Park Circle (L)", area: "Kharadi ⁣" },
  { landmark: "Kharadi-Hotel Redisson Blu (L)", area: "Kharadi ⁣" },
  { landmark: "Kharadi-By Pass-Hotel Tulsi(L)", area: "Kharadi ⁣" },
  { landmark: "Kharadi-Reliance Fresh Mart(L)", area: "Kharadi ⁣" },
  { landmark: "Kharadi-Reliance Fresh Mart(L)", area: "Kharadi ⁣" },
  { landmark: "Kharadi Corporation Bank (L)", area: "Kharadi ⁣" },
  { landmark: "Lullanagar-Mt Carmel School(L)", area: "Lullanagar ⁣" },
  { landmark: "Lullanagar-Netaji NGR gate(L)", area: "Lullanagar ⁣" },
  { landmark: "Kharadi-Corporation Bank (L)", area: "Kharadi ⁣" },
  { landmark: "Kharadi-Sainath Nagar Chowk(L)", area: "Kharadi ⁣" },
  { landmark: "Kiwale-Aadarsh NGR BusStop (S)", area: "Kiwale ⁣" },
  { landmark: "Kondhwa-Khadi Machine Chowk(L)", area: "Kondhwa ⁣" },
  { landmark: "Kondhwa-Konark Puram Gate (L)", area: "Kondhwa ⁣" },
  { landmark: "Kondhwa-BK Toughened Glass (L)", area: "" },
  { landmark: "Kondhwa-Sheetal Petrol pump(L)", area: "Kondhwa ⁣" },
  { landmark: "Kondhwa-VIT hostel (L)", area: "Kondhwa ⁣" },
  { landmark: "Koregaon Park-Koyla Rest (L)", area: "Koregaon Park ⁣" },
  { landmark: "Kothrud-Telephone Exchange (L)", area: "Kothrud ⁣" },
  { landmark: "Kothrud-Sutar Clinic (L)", area: "Kothrud ⁣" },
  { landmark: "Kothrud-Mahatma CHS Gate (L)", area: "Kothrud ⁣" },
  { landmark: "Kothrud-Shanti Ban society (L)", area: "Kothrud ⁣" },
  { landmark: "Kothrud-ShivtirthVadaCenter(L)", area: "Kothrud ⁣" },
  { landmark: "Kothrud-Woodlands Soc Gate (L)", area: "Kothrud ⁣" },
  { landmark: "Lakdi Pool-Garware School (L)", area: "Deccan ⁣" },
  { landmark: "Lohegaon-Khese Park Stop (L)", area: "Lohegaon ⁣" },
  { landmark: "New Sanghvi-KatePuram Chowk(S)", area: "Sangvi New ⁣" },
  { landmark: "New Sanghvi-Krishna Bazaar (S)", area: "Sangvi New ⁣" },
  { landmark: "New Sanghvi-Sai Chowk (S)", area: "Sangvi New ⁣" },
  { landmark: "Nibm-Nibm Road-Main Gate (L)", area: "NIBM ⁣" },
  { landmark: "Magarapatta-Konark Icon (L)", area: "MagarPatta ⁣" },
  { landmark: "Magarpatta-Ranka Jewellers(L)", area: "Hadapsar ⁣" },
  { landmark: "Old Sanghvi-Dhore NGR stop(M)", area: "Sangvi Old ⁣" },
  { landmark: "Old Sanghvi-Shitoley Chowk (M)", area: "Sangvi Old ⁣" },
  { landmark: "Old Sanghvi-ST colony stop (S)", area: "Sangvi Old ⁣" },
  { landmark: "Magarpatta City-Main Gate (L)", area: "Magarpatta City ⁣" },
  { landmark: "Parvati-LaxminarayanTheater(L)", area: "Parvati ⁣" },
  { landmark: "Pashan-Mont-Vert Corner (M)", area: "Pashan ⁣" },
  { landmark: "Pashan-Circle Gol Market (M)", area: "Pashan ⁣" },
  { landmark: "Paud RD-Anand NGR Entrance (L)", area: "Paud Road ⁣" },
  { landmark: "Paud RD-Ishanya Apartments (L)", area: "Paud Road ⁣" },
  { landmark: "Paud RD-Krishna Hospital (L)", area: "Paud Road ⁣" },
  { landmark: "Paud RD-Union BankOfIndia (L)", area: "Paud Road ⁣" },
  { landmark: "Pimple Gurav-Main bus stop (S)", area: "Pimple Gurav ⁣" },
  { landmark: "Pimple Gurav-Srushti Hotel (S)", area: "Pimple Gurav ⁣" },
  { landmark: "Malwadi-Last Bus Stop (L)", area: "Warje ⁣" },
  { landmark: "pimpleSaudagar-GovindGarden(S)", area: "pimple saudagar ⁣" },
  { landmark: "PimpleSaudagar-Kate Pump(S)", area: "pimple saudagar ⁣" },
  { landmark: "Pimple Saudagar-KonkaneChwk(S)", area: "pimple saudagar ⁣" },
  { landmark: "Pimple Saudagar-Kunal Ikon (S)", area: "pimple saudagar ⁣" },
  { landmark: "PimpleSaudagar-PlanetMille(S)", area: "pimple saudagar ⁣" },
  { landmark: "PimpleSaudagar-RajGardenHallS)", area: "pimple saudagar ⁣" },
  { landmark: "Market Yard-Suraj Hospital(L)", area: "Marketyard ⁣" },
  { landmark: "Marunji-Bank of Maharashtra(S)", area: "Marunji ⁣" },
  { landmark: "Nehru NGR-SantoshiMataChowk(M)", area: "Pimpri ⁣" },
  { landmark: "Pimpri-Nav Maha College (S)", area: "Pimpri ⁣" },
  { landmark: "Marunji-Life Republic (S)", area: "Marunji ⁣" },
  {
    landmark: "Marunji-Katraj Milk Corner (S)",
    area: "Marunji Kolte Patil Life Repub ",
  },
  { landmark: "Marunji-Bharat Medical (S)", area: "Marunji ⁣" },
  { landmark: "Pulgate-Pulgate Petrol Pump(L)", area: "Poolgate ⁣" },
  { landmark: "Mundhwa-Hadapsar Flyover (L)", area: "Mundhwa ⁣" },
  { landmark: "Mundhwa-RajashreeshauSchool(L)", area: "Mundhwa ⁣" },
  { landmark: "Pune Station-Coconut Grove (L)", area: "pune station ⁣" },
  { landmark: "Pune Station-RTO Bus Stop (L)", area: "pune station ⁣" },
  { landmark: "Pune station-Sadhu Vaswani (L)", area: "pune station ⁣" },
  { landmark: "Pune Station-AmbedkarBhavan(L)", area: "pune station ⁣" },
  { landmark: "Mundhwa-Post Office (L)", area: "Mundhwa ⁣" },
  { landmark: "Nalstop-Telephone Exchange (L)", area: "Nal stop ⁣" },
  { landmark: "Nana peth-Modern Bakery(L)", area: "Nana Peth ⁣" },
  { landmark: "NandedCity-Eco Park Garden (L)", area: "Nanded City ⁣" },
  { landmark: "NandedCity-Main gate (L)", area: "Nanded City ⁣" },
  { landmark: "Sangvi phata-Sangvi phata (S)", area: "Sangvi New ⁣" },
  { landmark: "SB Road-Symbiosys SBI Bank (L)", area: "Senapati Bapat Road ⁣" },
  { landmark: "NandedCity-Pawar School(L)", area: "Nanded City ⁣" },
  { landmark: "Narayan Peth-NMV Highschool(L)", area: "" },
  { landmark: "Narhe-SwamiNarayanTemple (L)", area: "Narhe ⁣" },
  { landmark: "Narhe- Zeal College(L)", area: "Narhe ⁣" },
  { landmark: "Narhe-Navale Hospital (L)", area: "Narhe ⁣" },
  { landmark: "ShaniwarPeth-PrabhatTalkies(L)", area: "Shaniwar Peth ⁣" },
  { landmark: "Nashik Phata-Signal (M)", area: "Kasarwadi ⁣" },
  { landmark: "Navi Peth-Alka talkies corn(L)", area: "Navi Peth ⁣" },
  { landmark: "Navi Peth-Kaka Halawai (L)", area: "Navi Peth ⁣" },
  { landmark: "Nigdi-Bhakti Shakti Chowk (M)", area: "Nigdi ⁣" },
  { landmark: "Nigdi-Kohinoor Arcade (M)", area: "Nigdi ⁣" },
  { landmark: "OOB-Wagholi-Samrudhi Sweets(L)", area: "" },
  { landmark: "Park street-Society gate (S)", area: "Kalewadi ⁣" },
  { landmark: "Hinjewadi PH3-Shell Pump (S)", area: "Hinjewadi ⁣" },
  { landmark: "Shukrawar Peth-Hotel Ganraj(L)", area: "Shukrawar Peth ⁣" },
  { landmark: "Shukrawar Peth-Phule Mandai(L)", area: "Shukrawar Peth ⁣" },
  { landmark: "Pimple Nilakh-PMT Bus Stop (S)", area: "Pimple Nilakh ⁣" },
  { landmark: "Pimpri-ST NGR-Fire Brigade (M)", area: "Pimpri ⁣" },
  { landmark: "Pimpri-AnnasahebMagarStdium(M)", area: "Pimpri ⁣" },
  { landmark: "Pradhikaran-AppuGharCorner (M)", area: "Pradhikaran Nigdi ⁣" },
  { landmark: "Pradhikaran-NigdiBig India (S)", area: "Pradhikaran Nigdi ⁣" },
  { landmark: "Pradhikaran-Sambhaji Chowk (S)", area: "Pradhikaran Nigdi ⁣" },
  { landmark: "Somwar Peth-NarpatgiriChowk(L)", area: "Somwar Peth ⁣" },
  { landmark: "Punawale-Pulse Hospital (S)", area: "Punawale ⁣" },
  { landmark: "Punawale-18 Latitude Mall (M)", area: "Punawale ⁣" },
  { landmark: "Punawale-LotusBusinesSchool(M)", area: "Punawale ⁣" },
  { landmark: "Swargate-Seven Loves Chowk (L)", area: "Swargate ⁣" },
  { landmark: "Swargate-Sanas Ground (L)", area: "Swargate ⁣" },
  { landmark: "Punawale-Sai Petrol Pump (M)", area: "Punawale ⁣" },
  { landmark: "Punawale-ServiceRoadDominos(S)", area: "Punawale ⁣" },
  { landmark: "Swargate-Vega Centre (L)", area: "Swargate ⁣" },
  { landmark: "Rahatani - LIC office (S)", area: "Rahatni ⁣" },
  { landmark: "Rakshak Chowk-Rakshak Chowk(S)", area: "Rakshak Chowk ⁣" },
  { landmark: "Thergaon-AdityBirlaHospital(S)", area: "Thergaon ⁣" },
  { landmark: "Thergaon-Rosewood Hotel (S)", area: "Thergaon ⁣" },
  { landmark: "Ravet-Celestial City Corner(M)", area: "Ravet ⁣" },
  { landmark: "Ravet-Creative Academy (M)", area: "Ravet ⁣" },
  { landmark: "Ravet-Live Fit Gym Corner (S)", area: "Ravet ⁣" },
  { landmark: "Ravet-Sentosa Resorts (S)", area: "Ravet ⁣" },
  { landmark: "Rupe NGR-TriveniNagarCorner(M)", area: "Rupee nagar ⁣" },
  { landmark: "Sadashiv Peth-Alka talkies(L)", area: "Sadashiv Peth ⁣" },
  { landmark: "Sadashiv Peth-S P College (L)", area: "Sadashiv Peth ⁣" },
  { landmark: "SahkarNGR-Bhapkar Pump(L)", area: "Sahakar Nagar ⁣" },
  { landmark: "SahkarNGR-GajananMandir(L)", area: "Sahakar Nagar ⁣" },
  { landmark: "SahkarNGR-MitramandalChouk(L)", area: "Sahakar Nagar ⁣" },
  { landmark: "SahkarNGR-Rawat Brothers (L)", area: "Sahakar Nagar ⁣" },
  { landmark: "SahkarNGR-Vivekanand Chowk(L)", area: "Sahakar Nagar ⁣" },
  { landmark: "VishrantWadi-Prateek Nagar (L)", area: "Vishrantwadi ⁣" },
  { landmark: "VishrantWadi-Chowk (L)", area: "Vishrantwadi ⁣" },
  { landmark: "SalunkeVihar-Telephone Exch(L)", area: "Wanowrie ⁣" },
  { landmark: "Shaniwarwada-Maha House(L)", area: "Kasaba Peth ⁣" },
  { landmark: "Deccan-Hotel Savera (L)", area: "Shivaji Nagar ⁣" },
  { landmark: "WakdeWadi-BUBhandari (L)", area: "Wakdewadi ⁣" },
  { landmark: "Walekarwadi-ChinchwadeFarms(M)", area: "Walhekarwadi ⁣" },
  { landmark: "Walekarwadi-Palika School (M)", area: "Walhekarwadi ⁣" },
  { landmark: "Wanowrie-AnusuyaEnclave CHS(L)", area: "Wanowrie ⁣" },
  { landmark: "Wanowrie-Jambhulkar chowk (L)", area: "Wanowrie ⁣" },
  { landmark: "Wanowrie-Kedari Petrol Pump(L)", area: "Wanowrie ⁣" },
  { landmark: "Warje-Aaditya Graden City (L)", area: "Warje ⁣" },
  { landmark: "Warje-Runwal Meadows Gate (L)", area: "Warje ⁣" },
  { landmark: "Warje Naka-After bridge (L)", area: "Warje ⁣" },
  { landmark: "Shivaji NGR-E Square (L)", area: "Shivaji Nagar ⁣" },
  { landmark: "Shivaji NGR-FC main gate (L)", area: "Shivaji Nagar ⁣" },
  { landmark: "Yerawada-BEG bus stop (L)", area: "Yerwada ⁣" },
  { landmark: "Yerawada-Golf Club circle (L)", area: "Yerwada ⁣" },
  { landmark: "Shivaji NGR-HardikarHospita(L)", area: "Shivaji Nagar ⁣" },
  { landmark: "Shivaji NGR-Kamgar Putala (L)", area: "Shivaji Nagar ⁣" },
  { landmark: "Shivaji NGR-Central Mall (L)", area: "Shivaji Nagar ⁣" },
  { landmark: "Shivaji NGR-Post Office (L)", area: "Shivaji Nagar ⁣" },
  { landmark: "Shivane-Harishkumar Shopee (L)", area: "Shivane ⁣" },
  { landmark: "Sinhagad RD-VitthalWadi SBI(L)", area: "Sinhagad Road ⁣" },
  { landmark: "Sinhgad RD-Santosh Hall (L)", area: "Sinhagad Road ⁣" },
  { landmark: "Sinhgad RD-Hotel Vishwas (L)", area: "Sinhagad Road ⁣" },
  { landmark: "Sinhgad RD-Manik Baug (L)", area: "Singhgad Road ⁣" },
  { landmark: "Sinhgad RD-NirmiteeShowroom(L)", area: "Sinhagad Road ⁣" },
  { landmark: "SinhgadRoad-Rajaram Briedge(L)", area: "Sinhagad Road ⁣" },
  { landmark: "Sinhgad RD-Suncity corner (L)", area: "Sinhagad Road ⁣" },
  { landmark: "Sopan Baug Corner (L)", area: "Sopan Baug ⁣" },
  { landmark: "Spine Road-Spine City Mall (L)", area: "Chikhali ⁣" },
  { landmark: "Sukhsagar Nagar-Lake View (L)", area: "Sukhsagar Nagar ⁣" },
  { landmark: "SusRD-AbhinavKala Vidyalaya(S)", area: "Sus Road ⁣" },
  { landmark: "Sus Road-Supreme HQ (S)", area: "Sus Road ⁣" },
  { landmark: "Tathawade -SHANI MANDIR (S)", area: "Tathwade ⁣" },
  { landmark: "Pimpri-Ashok theatre Chowk (S)", area: "Pimpri ⁣" },
  { landmark: "Tathwade-Balaji Law College(S)", area: "Tathwade ⁣" },
  { landmark: "Tathwade-IndiraCollage Gate(S)", area: "Tathwade ⁣" },
  { landmark: "Tathwade-JSPM Main Gate(S)", area: "Tathwade ⁣" },
  { landmark: "Thermax Chowk - Hdfc Corner(M)", area: "Thermax chowk ⁣" },
  { landmark: "Wanowri-PunjabNationalBank (L)", area: "" },
  { landmark: "PimpleGurav-OmSaiTea corner(M)", area: "Pimple Gurav ⁣" },
  { landmark: "Tingre NGR-509 Bus Stop (L)", area: "Tingre Nagar ⁣" },
  { landmark: "Tingre NGR-Sanjay Park Corn(L)", area: "Lohegaon ⁣" },
  { landmark: "Tingre NGR-SawantPetrolPump(L)", area: "Tingre Nagar ⁣" },
  { landmark: "University Circle- Bus Stop(M)", area: "University Circle ⁣" },
  { landmark: "Uttamnagar-Telephone Exch (L)", area: "Uttam Nagar ⁣" },
  { landmark: "Vadgaon BK-Funtime Theatre (L)", area: "VADGAON BUDRUK ⁣" },
  { landmark: "Vadgaon BK-Indian Hume Pipe(L)", area: "VADGAON BUDRUK ⁣" },
  { landmark: "PimpleSaudagar-JeevanJyoti (S)", area: "pimple saudagar ⁣" },
  { landmark: "VadgaonBudruk-DeccanPavilion-L", area: "VADGAON BUDRUK ⁣" },
  { landmark: "VadgaonSheri-BollywoodSpice(L)", area: "Vadgaonsheri ⁣" },
  { landmark: "VadgaonSheri-AnandPark Stop(L)", area: "Vadgaonsheri ⁣" },
  { landmark: "Vadgaonsheri-Brahma Suncity(L)", area: "Vadgaonsheri ⁣" },
  { landmark: "Vadgaosheri-SaharaResturant(L)", area: "Vadgaonsheri ⁣" },
  { landmark: "Vadgaosheri-Somnath Mandir (L)", area: "Vadgaonsheri ⁣" },
  { landmark: "Vimanagar-Symbiosis (SIMC) (L)", area: "VIMANAGAR" },
  { landmark: "Vishal Nagar-Hotel Akshat (S)", area: "Vishal Nagar ⁣" },
  { landmark: "Vishal Nagar-DP raod Corner(S)", area: "Vishal Nagar ⁣" },
  { landmark: "Yerawada-Sangamwadi Corner(L)", area: "Yerwada ⁣" },
  { landmark: "Vit Hostel Kondhwa - (L)", area: "Kondhwa ⁣" },
  { landmark: "Wagholi-WagheshwarTempleOOB(L)", area: "Wagholi ⁣" },
  { landmark: "Wakad-Life Point Hospital (S)", area: "Wakad ⁣" },
  { landmark: "Wakad-Garve Hyundai (S)", area: "Wakad ⁣" },
  { landmark: "Wakad-Whisling Palms Gate (S)", area: "Wakad ⁣" },
  { landmark: "Salunkhe Vihar-BankofIndia (L)", area: "Wanowrie ⁣" },
  { landmark: "Xrbia-Township Marunji OOB (M)", area: "" },
  { landmark: "Yamuna NGR-Kanhaiya sweets (M)", area: "Yamuna Nagar ⁣" },
  { landmark: "Yamuna NGR-Lic YamunaNGR (M)", area: "Yamuna Nagar ⁣" },
  {
    landmark: "AMBEGAON POTDAR INT SCHOOL (L) ⁣",
    area: "Ambegaon Budruk left ⁣",
  },
  { landmark: "AMBEGOAN NEAR D-MART(L) ⁣", area: "Ambegaon Budruk left ⁣" },
  { landmark: "MANSAVI SOCI DATTANAGAROOB(L) ⁣", area: "AmbegoanDattaNagar" },
  { landmark: "BHOSARI – BHOSARI GARDEN (M) ⁣", area: "Bhosari ⁣" },
  { landmark: "CHARHOLI BK TAPKIR CHOWK (L) ⁣", area: "Charholi Budruk ⁣" },
  { landmark: "CHARHOLI PHATA SIGNAL (L)", area: "Charholi Budruk ⁣" },
  { landmark: "CHARHOLI SAIRAJ KARAYALAY(L)", area: "Charholi Budruk ⁣" },
  { landmark: "CHARHOLI SAITIRUPATI GREENS(L) ⁣", area: "Charholi Budruk ⁣" },
  { landmark: "LOHEGAON-PRIDEWORLDCITYOOB (L) ⁣", area: "Charholi Budruk ⁣" },
  { landmark: "BTKAWADE-KALUBAI CHOWK (L) ⁣", area: "Fatimanagar " },
  { landmark: "INFOSYS PH-2 GATE-1 TCG ⁣", area: "Hinjewadi ⁣" },
  { landmark: "MEGHAPOLIS PH-3 ⁣", area: "Hinjewadi ⁣" },
  { landmark: "PH -1 INFOSYS GATE-1 ⁣", area: "Hinjewadi ⁣" },
  { landmark: "KHADKI ORDNANCE FACTORYCLUB(L) ⁣", area: "Khadaki ⁣" },
  { landmark: "LOHEGAON - JIJAU CHOWK (L) ⁣", area: "Lohegaon ⁣" },
  { landmark: "VIBGYOR SCHOOL MGRPATTA (L) ", area: "MagarPatta ⁣" },
  { landmark: "MOSHI - BHARAT MATA CHOWK (L)", area: "Moshi ⁣" },
  { landmark: "GOVIND GARDEN (S) ⁣", area: "pimple saudagar ⁣" },
  { landmark: "PIMPLESAUDAGAR-SHIVARGARDEN(S) ⁣", area: "pimple saudagar ⁣" },
  { landmark: "PUNAWALE-DMART READY (M) ⁣", area: "Punawale ⁣" },
  { landmark: "PUNAWALE-KOYATE WASTI CHOWK(M) ⁣", area: "Punawale ⁣" },
  { landmark: "RAVET -YASHASHREE HOSPITAL (M) ⁣", area: "Ravet ⁣" },
  { landmark: "PHADGATE POLICE CHOWKY(L) ⁣", area: "Shukrawar Peth ⁣" },
  { landmark: "WAGHOLI-KESNAND PHATA OOB(L) ⁣", area: "Wagholi ⁣" },
  { landmark: "WAGHOLI-KHANDVENGR CHOWKOOB(L) ⁣", area: "Wagholi ⁣" },
  { landmark: "WAGHOLI-PAWARWASTI STOPOOB(VL) ⁣", area: "Wagholi ⁣" },
  { landmark: "WANOWRIE-BANK OF MAHA (L) ⁣", area: "Wanowrie ⁣" },
];
